const fs = require('fs');
const code = [
  "import React from 'react';",
  "import { X, Printer, MessageSquare, CheckCircle2, ShieldCheck } from 'lucide-react';",
  "",
  "export function ReceiptModal({ project, paymentData, onClose }) {",
  "  if (!project && !paymentData) return null;",
  "",
  "  const clientName    = project?.clientName  || paymentData?.clientName  || 'Valued Client';",
  "  const clientCode    = project?.clientCode  || paymentData?.clientCode  || 'FIX-CLIENT-001';",
  "  const domain        = project?.domain      || paymentData?.domain      || 'clientwebsite.in';",
  "  const contactPerson = project?.contactPerson || paymentData?.contactPerson || '';",
  "  const phone         = project?.phone       || paymentData?.phone       || '';",
  "",
  "  const receiptNo     = project?.receiptNumber || paymentData?.receiptNumber",
  "    || ('FIX-RCPT-' + new Date().getFullYear() + '-' + String(project?.id || Date.now()).slice(-4));",
  "  const paymentMethod = project?.paymentMethod || paymentData?.paymentMethod || 'UPI';",
  "  const txRef         = project?.transactionReference || paymentData?.transactionReference",
  "    || (paymentMethod.includes('Cash') ? 'CASH-VERIFIED' : ('UPI/' + Math.floor(100000000000 + Math.random() * 900000000000)));",
  "  const paymentDate   = paymentData?.paymentDate || new Date().toISOString().split('T')[0];",
  "",
  "  const totalNum   = paymentData?.rawAmount",
  "    || parseInt(String(project?.totalBudget || paymentData?.amount || '35000').replace(/[^0-9]/g, ''), 10) || 35000;",
  "  const balanceNum = parseInt(String(project?.balanceDue || '').replace(/[^0-9]/g, ''), 10) || 0;",
  "",
  "  const digitalSignatureHash = paymentData?.digitalSignatureHash",
  "    || ('sha256:7f8e9a2b' + receiptNo.replace(/[^0-9]/g, '') + '3c4d5e6f1a8b9c0d');",
  "",
  "  const clientDomain = domain && domain !== 'clientwebsite.in'",
  "    ? domain : (project?.domain || paymentData?.domain || 'clientdomain.in');",
  "",
  "  const isAdvanceMilestone = project?.invoiceType?.includes('Advance')",
  "    || (project?.paymentStatus && !project?.paymentStatus.includes('Paid in Full') && totalNum < 15000);",
  "  const isFinalMilestone   = project?.invoiceType?.includes('Final');",
  "  const hasAddons          = project?.addons || {};",
  "",
  "  let lineItems = [];",
  "  if (isAdvanceMilestone) {",
  "    const base = [",
  "      { name: 'Domain Registration (' + clientDomain + ') and SSL Certificate', amount: 999 },",
  "      { name: 'Managed Cloud VPS Server and NVMe Hosting (1 Year)',              amount: 2499 },",
  "      { name: 'Transactional SMS and OTP Security Gateway',                      amount: 499 },",
  "    ];",
  "    let running = 3997;",
  "    if (hasAddons.paymentGateway) { base.push({ name: 'Payment Gateway Integration (UPI/Razorpay)', amount: 1499 }); running += 1499; }",
  "    if (hasAddons.whatsappAlerts) { base.push({ name: 'WhatsApp Order and Booking Alert Engine',    amount: 999  }); running += 999; }",
  "    if (hasAddons.seoPack)        { base.push({ name: 'Google Business SEO and Maps Visibility',    amount: 1200 }); running += 1200; }",
  "    if (totalNum > running)       { base.push({ name: 'System Architecture and UI/UX Prototype',    amount: totalNum - running }); }",
  "    lineItems = base;",
  "  } else if (isFinalMilestone) {",
  "    lineItems = [",
  "      { name: 'Full-Stack Web App - Production Handover and Deployment', amount: Math.floor(totalNum * 0.75) },",
  "      { name: '1-Year Bug-Fix SLA and Technical Warranty',               amount: totalNum - Math.floor(totalNum * 0.75) },",
  "    ];",
  "  } else if (totalNum >= 8000) {",
  "    const sv = 2499, dm = 999, ot = 499, dv = totalNum - sv - dm - ot;",
  "    lineItems = [",
  "      { name: 'Full-Stack Web Development and Responsive UI/UX Design', amount: dv },",
  "      { name: 'Managed Cloud VPS Server and Hosting (1 Year)',          amount: sv },",
  "      { name: 'Domain Registration (' + clientDomain + ') and SSL',     amount: dm },",
  "      { name: 'Transactional SMS and OTP Gateway',                      amount: ot },",
  "    ];",
  "  } else {",
  "    lineItems = [{ name: project?.service || 'Web Engineering and Technical Services', amount: totalNum }];",
  "  }",
  "",
  "  const advancePaid   = project?.advancePaidAmount || 0;",
  "  const advanceRef    = project?.advanceRef || '';",
  "  const showAdvance   = (isFinalMilestone || project?.invoiceType?.includes('Final')) && advancePaid > 0;",
  "  const amountPaidNow = showAdvance ? totalNum - advancePaid : totalNum;",
  "",
  "  const getWA = () => {",
  "    const cp = String(phone || '').replace(/[^0-9]/g, '');",
  "    const t = encodeURIComponent(",
  "      'Hello ' + (contactPerson || clientName) + '!\\n\\nFixkar Payment Receipt\\nReceipt: ' + receiptNo +",
  "      '\\nClient: ' + clientName + ' (' + clientCode + ')' +",
  "      '\\nAmount Paid: Rs. ' + amountPaidNow.toLocaleString('en-IN') +",
  "      '\\nMode: ' + paymentMethod + '\\nRef: ' + txRef +",
  "      '\\nBalance Due: Rs. ' + balanceNum.toLocaleString('en-IN') +",
  "      '\\n\\nSupport: www.fixkar.co.in | support@fixkar.co.in'",
  "    );",
  "    return 'https://wa.me/' + (cp.startsWith('91') ? cp : '91' + cp) + '?text=' + t;",
  "  };",
  "",
  "  const fmtDate = (d) => {",
  "    try { return new Date(d).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' }); }",
  "    catch (err) { return d; }",
  "  };",
  "",
  "  const INV_NO = project?.invoiceNumber || receiptNo.replace('RCPT', 'INV');",
  "",
  "  const bdg = { display: 'inline-block', color: '#fff', fontSize: '0.62rem', fontWeight: 800, padding: '2px 9px', borderRadius: '4px', textTransform: 'uppercase', letterSpacing: '0.06em', marginBottom: '5px' };",
  "",
  "  return (",
  "    <div style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.88)', backdropFilter: 'blur(14px)', zIndex: 999999, display: 'flex', alignItems: 'center', justifyContent: 'center', padding: '20px 16px', overflowY: 'auto' }}>",
  "      <div style={{ width: '100%', maxWidth: '520px', margin: 'auto', display: 'flex', flexDirection: 'column', gap: '10px' }}>",
  "",
  "        {/* Action Bar */}",
  "        <div className=\"no-print\" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', background: '#111827', border: '1px solid #1F2937', borderRadius: '10px', padding: '10px 16px' }}>",
  "          <span style={{ color: '#F1F5F9', fontWeight: 700, fontSize: '0.82rem' }}>",
  "            {isAdvanceMilestone ? 'Advance Receipt' : 'Payment Receipt'} &mdash; {receiptNo}",
  "          </span>",
  "          <div style={{ display: 'flex', gap: '8px', alignItems: 'center' }}>",
  "            <button onClick={() => window.print()} style={{ background: '#2563EB', border: 'none', color: '#fff', padding: '6px 14px', borderRadius: '6px', fontSize: '0.74rem', fontWeight: 700, cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '5px' }}>",
  "              <Printer size={13} /> Print / PDF",
  "            </button>",
  "            <a href={getWA()} target=\"_blank\" rel=\"noreferrer\" style={{ background: '#16A34A', color: '#fff', padding: '6px 14px', borderRadius: '6px', fontSize: '0.74rem', fontWeight: 700, textDecoration: 'none', display: 'flex', alignItems: 'center', gap: '5px' }}>",
  "              <MessageSquare size={13} /> WhatsApp",
  "            </a>",
  "            <button onClick={onClose} style={{ background: 'none', border: 'none', color: '#6B7280', cursor: 'pointer', padding: '4px', display: 'flex' }}><X size={18} /></button>",
  "          </div>",
  "        </div>",
  "",
  "        {/* Receipt Paper */}",
  "        <div id=\"printable-receipt-sheet\" style={{ background: '#FFFFFF', borderRadius: '12px', overflow: 'hidden', boxShadow: '0 24px 60px rgba(0,0,0,0.7)', fontFamily: \"'Inter','Segoe UI',Arial,sans-serif\" }}>",
  "",
  "          {/* Dark Header */}",
  "          <div style={{ background: '#0F172A', padding: '20px 24px 16px' }}>",
  "            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>",
  "",
  "              {/* Logo */}",
  "              <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>",
  "                <div style={{ flexShrink: 0, width: '46px', height: '46px', position: 'relative' }}>",
  "                  <img src=\"/fixkar-logo.png\" alt=\"Fixkar\"",
  "                    style={{ width: '46px', height: '46px', objectFit: 'contain', borderRadius: '10px', background: '#1E293B', padding: '5px', display: 'block' }}",
  "                    onError={(e) => { e.currentTarget.style.display='none'; e.currentTarget.nextSibling.style.display='flex'; }}",
  "                  />",
  "                  <div style={{ display:'none', position:'absolute', inset:0, borderRadius:'10px', background:'linear-gradient(135deg,#2563EB,#1E40AF)', alignItems:'center', justifyContent:'center', fontSize:'1.4rem', fontWeight:900, color:'#fff', letterSpacing:'-0.04em' }}>F</div>",
  "                </div>",
  "                <div>",
  "                  <div style={{ color: '#FFFFFF', fontWeight: 900, fontSize: '1.35rem', letterSpacing: '-0.03em', lineHeight: 1 }}>Fixkar</div>",
  "                  <div style={{ color: '#64748B', fontSize: '0.63rem', fontWeight: 500, marginTop: '3px', textTransform: 'uppercase', letterSpacing: '0.05em' }}>Web &amp; IT Studio</div>",
  "                </div>",
  "              </div>",
  "",
  "              {/* Receipt ID */}",
  "              <div style={{ textAlign: 'right' }}>",
  "                <div style={{ ...bdg, background: isAdvanceMilestone ? '#1D4ED8' : '#166534' }}>",
  "                  {isAdvanceMilestone ? 'Advance Receipt' : 'Payment Receipt'}",
  "                </div>",
  "                <div style={{ color: '#E2E8F0', fontWeight: 800, fontSize: '0.85rem', fontFamily: 'monospace', display: 'block' }}>{receiptNo}</div>",
  "                <div style={{ color: '#64748B', fontSize: '0.64rem', marginTop: '3px' }}>Invoice: <span style={{ fontFamily: 'monospace', color: '#94A3B8' }}>{INV_NO}</span></div>",
  "              </div>",
  "            </div>",
  "",
  "            {/* Address bar */}",
  "            <div style={{ display: 'flex', gap: '12px', flexWrap: 'wrap', color: '#475569', fontSize: '0.63rem', marginTop: '14px', paddingTop: '10px', borderTop: '1px solid rgba(255,255,255,0.07)' }}>",
  "              <span>Alamnagar, Lucknow UP 226017</span>",
  "              <span>&middot;</span>",
  "              <span>support@fixkar.co.in</span>",
  "              <span>&middot;</span>",
  "              <span>www.fixkar.co.in</span>",
  "            </div>",
  "          </div>",
  "",
  "          {/* White Body */}",
  "          <div style={{ padding: '20px 24px', color: '#0F172A' }}>",
  "",
  "            {/* Client + Date row */}",
  "            <div style={{ display: 'flex', justifyContent: 'space-between', gap: '16px', paddingBottom: '14px', borderBottom: '1px solid #E2E8F0', marginBottom: '16px' }}>",
  "              <div>",
  "                <div style={{ fontSize: '0.6rem', fontWeight: 700, color: '#94A3B8', textTransform: 'uppercase', letterSpacing: '0.06em', marginBottom: '3px' }}>Billed To</div>",
  "                <div style={{ fontWeight: 800, fontSize: '0.95rem', color: '#0F172A' }}>{clientName}</div>",
  "                <div style={{ fontSize: '0.7rem', color: '#64748B', marginTop: '3px' }}>",
  "                  <span style={{ fontFamily: 'monospace', color: '#334155' }}>{clientCode}</span>",
  "                  {clientDomain ? <span>&nbsp;&middot;&nbsp;{clientDomain}</span> : null}",
  "                </div>",
  "                {contactPerson ? <div style={{ fontSize: '0.68rem', color: '#64748B', marginTop: '2px' }}>{contactPerson}</div> : null}",
  "              </div>",
  "              <div style={{ textAlign: 'right', flexShrink: 0 }}>",
  "                <div style={{ fontSize: '0.6rem', fontWeight: 700, color: '#94A3B8', textTransform: 'uppercase', letterSpacing: '0.06em', marginBottom: '3px' }}>Date / Mode</div>",
  "                <div style={{ fontWeight: 700, fontSize: '0.88rem', color: '#0F172A' }}>{fmtDate(paymentDate)}</div>",
  "                <div style={{ fontSize: '0.7rem', color: '#2563EB', fontWeight: 600, marginTop: '3px' }}>{paymentMethod}</div>",
  "              </div>",
  "            </div>",
  "",
  "            {/* Items */}",
  "            <table style={{ width: '100%', borderCollapse: 'collapse' }}>",
  "              <thead>",
  "                <tr>",
  "                  <th style={{ width: '22px', textAlign: 'left', padding: '0 0 7px', fontSize: '0.6rem', fontWeight: 700, color: '#94A3B8', textTransform: 'uppercase', letterSpacing: '0.05em', borderBottom: '1.5px solid #1E293B' }}>#</th>",
  "                  <th style={{ textAlign: 'left', padding: '0 10px 7px', fontSize: '0.6rem', fontWeight: 700, color: '#94A3B8', textTransform: 'uppercase', letterSpacing: '0.05em', borderBottom: '1.5px solid #1E293B' }}>Description</th>",
  "                  <th style={{ textAlign: 'right', padding: '0 0 7px', fontSize: '0.6rem', fontWeight: 700, color: '#94A3B8', textTransform: 'uppercase', letterSpacing: '0.05em', borderBottom: '1.5px solid #1E293B', whiteSpace: 'nowrap' }}>Amount (Rs.)</th>",
  "                </tr>",
  "              </thead>",
  "              <tbody>",
  "                {lineItems.map((item, i) => (",
  "                  <tr key={i}>",
  "                    <td style={{ padding: '9px 0', verticalAlign: 'top', fontSize: '0.7rem', color: '#94A3B8', fontWeight: 600, borderBottom: '1px solid #F1F5F9' }}>{i + 1}</td>",
  "                    <td style={{ padding: '9px 10px', verticalAlign: 'top', fontSize: '0.8rem', color: '#1E293B', fontWeight: 600, lineHeight: 1.4, borderBottom: '1px solid #F1F5F9' }}>{item.name}</td>",
  "                    <td style={{ padding: '9px 0', verticalAlign: 'top', textAlign: 'right', fontSize: '0.82rem', fontWeight: 700, color: '#0F172A', whiteSpace: 'nowrap', borderBottom: '1px solid #F1F5F9' }}>",
  "                      {item.amount.toLocaleString('en-IN')}",
  "                    </td>",
  "                  </tr>",
  "                ))}",
  "              </tbody>",
  "            </table>",
  "",
  "            {/* Totals */}",
  "            <div style={{ marginTop: '10px', paddingTop: '10px', borderTop: '2px solid #0F172A' }}>",
  "              {showAdvance && (",
  "                <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.76rem', color: '#475569', marginBottom: '6px' }}>",
  "                  <span>Advance Paid {advanceRef ? '(' + advanceRef + ')' : '(Earlier)'}</span>",
  "                  <span style={{ color: '#2563EB', fontWeight: 700 }}>- Rs. {advancePaid.toLocaleString('en-IN')}</span>",
  "                </div>",
  "              )}",
  "              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>",
  "                <span style={{ fontSize: '0.87rem', fontWeight: 700, color: '#0F172A' }}>Total Paid</span>",
  "                <span style={{ fontSize: '1.28rem', fontWeight: 900, color: '#16A34A' }}>Rs. {amountPaidNow.toLocaleString('en-IN')}</span>",
  "              </div>",
  "              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginTop: '4px' }}>",
  "                <span style={{ fontSize: '0.75rem', color: '#64748B' }}>Balance Due</span>",
  "                <span style={{ fontSize: '0.87rem', fontWeight: 800, color: balanceNum === 0 ? '#16A34A' : '#DC2626' }}>",
  "                  Rs. {balanceNum.toLocaleString('en-IN')}",
  "                </span>",
  "              </div>",
  "            </div>",
  "",
  "            {/* Transaction Ref */}",
  "            <div style={{ marginTop: '16px', background: '#F8FAFC', border: '1px solid #E2E8F0', borderRadius: '8px', padding: '10px 14px' }}>",
  "              <div style={{ fontSize: '0.6rem', fontWeight: 700, color: '#94A3B8', textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: '4px' }}>Transaction Reference</div>",
  "              <div style={{ fontFamily: 'monospace', fontSize: '0.8rem', fontWeight: 700, color: '#2563EB', wordBreak: 'break-all' }}>{txRef}</div>",
  "            </div>",
  "",
  "            {/* Footer */}",
  "            <div style={{ marginTop: '16px', paddingTop: '14px', borderTop: '1px dashed #CBD5E1', display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: '8px' }}>",
  "              <div>",
  "                <div style={{ display: 'flex', alignItems: 'center', gap: '5px', color: '#16A34A', fontSize: '0.68rem', fontWeight: 700 }}>",
  "                  <ShieldCheck size={13} />",
  "                  Computer Generated - No Signature or Stamp Required",
  "                </div>",
  "                <div style={{ fontSize: '0.58rem', color: '#94A3B8', marginTop: '3px', fontFamily: 'monospace' }}>",
  "                  {digitalSignatureHash.slice(0, 30)}...",
  "                </div>",
  "              </div>",
  "              <div style={{ display: 'inline-flex', alignItems: 'center', gap: '4px', background: '#DCFCE7', border: '1px solid #86EFAC', borderRadius: '5px', padding: '4px 10px', fontSize: '0.66rem', fontWeight: 800, color: '#166534' }}>",
  "                <CheckCircle2 size={12} /> Fixkar Verified",
  "              </div>",
  "            </div>",
  "",
  "          </div>",
  "        </div>",
  "",
  "      </div>",
  "    </div>",
  "  );",
  "}",
].join('\n');

fs.writeFileSync('src/components/admin/ReceiptModal.jsx', code, 'utf8');
console.log('Written OK, lines:', code.split('\n').length);