import React, { createContext, useContext, useState } from 'react';

const translations = {
  en: {
    nav: {
      brandTag: 'WEB DEVELOPMENT',
      home: 'Home',
      services: 'Services',
      work: 'Our Work',
      howItWorks: 'Process',
      about: 'About',
      contact: 'Contact',
      getQuote: 'Get a Quote',
    },
    hero: {
      tag: 'FIXKAR / WEB DEVELOPMENT & DIGITAL SOLUTIONS',
      headlinePre: 'Websites & Web Systems',
      headlineAccent: 'Built Around Your Business.',
      description:
        'From professional business websites to custom portals, dashboards and web applications, Fixkar builds secure, responsive and scalable digital solutions designed around real business requirements.',
      ctaPrimary: 'Start Your Project →',
      ctaAI: 'Ask Fixkar AI Copilot 🤖',
      ctaSecondary: 'View Our Work',
      metricUptime: 'Business Focused',
      metricUptimeLabel: 'Built Around Requirements (No Generic Templates)',
      metricSpeed: 'Full Ownership',
      metricSpeedLabel: '100% Code & Asset Ownership',
      metricDelivery: 'Direct Access',
      metricDeliveryLabel: 'Senior Developer Collaboration',
    },
    trust: {
      label: 'PRODUCTION WEB SYSTEMS POWERING REAL BUSINESSES',
      sub: 'Custom web solutions supporting real business operations',
    },
    homeFacts: {
      eyebrow: 'WHY FIXKAR',
      title: 'Technology Built Around Real Business Needs',
      tagline: 'Every project starts with understanding your operational requirements rather than forcing a generic template.',
      c1Badge: 'CLEAN & MAINTAINABLE',
      c1Title: 'Modern Development',
      c1Desc: 'Clean, maintainable solutions built with modern web technologies and structured for long-term expansion.',
      c2Badge: 'BUSINESS FOCUSED',
      c2Title: 'Built Around Your Workflow',
      c2Desc: 'From admin dashboards to student portals, every feature is designed around how your business actually operates.',
      c3Badge: 'SECURITY & SUPPORT',
      c3Title: 'Security & Ongoing Support',
      c3Desc: 'Authentication, data access, and sensitive functionality are handled with security in mind, backed by reliable ongoing maintenance.',
      ctaTag: 'HAVE A PROJECT IN MIND?',
      ctaTitle: 'Let’s build the right web solution for your business.',
      ctaDesc: 'Explore our delivered work or discuss your requirements directly with our team.',
      ctaQuoteBtn: 'Calculate Project Quote →',
      ctaWorkBtn: 'View Our Work',
    },
    services: {
      eyebrow: '01 / OUR SERVICES',
      title: 'Web Development & Digital Solutions',
      tagline: 'Professional websites, custom applications, and managed technical services designed around your business goals.',
      s1: {
        num: '01',
        title: 'Website Development',
        desc: 'Professional websites designed around your brand, audience and business goals—from company websites and portfolios to education and service-based platforms.',
        tech: ['Business Websites', 'Institute Portals', 'Responsive Design', 'SEO Ready', 'Fast Load'],
      },
      s2: {
        num: '02',
        title: 'Custom Web Applications',
        desc: 'Custom portals, dashboards, management systems and web-based tools designed around your workflow and operational requirements.',
        tech: ['Admin Dashboards', 'Client Portals', 'Authentication', 'Role Management', 'Cloud Database'],
      },
      s3: {
        num: '03',
        title: 'E-Commerce Development',
        desc: 'Modern online stores with product management, orders, customer experiences, payments and administrative controls.',
        tech: ['Product Catalogs', 'Order Management', 'UPI & Card Payments', 'Customer Accounts'],
      },
      s4: {
        num: '04',
        title: 'Maintenance & Managed Services',
        desc: 'Supporting services including website maintenance, hosting management, backups, security support, and OTP/mobile verification workflows.',
        tech: ['Website Maintenance', 'Hosting Management', 'Backups & Security', 'OTP Verification'],
      },
    },
    work: {
      eyebrow: '02 / OUR WORK',
      title: 'Real Projects Engineered for Real Clients',
      tagline: 'Take a look at actual production platforms we have built for businesses across hospitality, electronics, and service booking.',
      scaterers: {
        title: 'S Caterers & Events',
        category: 'Hospitality & Event Management',
        benefit: 'Custom catering platform with interactive menu planning, per-plate price estimation, and direct WhatsApp enquiry flow.',
        tech: 'Website · Interactive Menu Estimator · Lead Dispatch · Mobile Responsive',
        stat1Label: 'Menu Estimator',
        stat1Val: 'Interactive Flow',
        stat2Label: 'Inquiry Dispatch',
        stat2Val: 'Direct WhatsApp',
        stat3Label: 'Project Status',
        stat3Val: 'Delivered & Live',
      },
      ecofone: {
        title: 'Ecofone',
        category: 'E-Commerce & Device Valuation',
        benefit: 'Smartphone trade-in platform featuring a 3-step evaluation engine, instant valuation, and payment gateway integration.',
        tech: 'E-Commerce · Valuation Engine · Admin Dashboard · UPI Payments',
        stat1Label: 'Device Valuation',
        stat1Val: '3-Step Flow',
        stat2Label: 'Payment Gateway',
        stat2Val: 'Razorpay UPI',
        stat3Label: 'Project Status',
        stat3Val: 'Delivered & Live',
      },
      singhs: {
        title: "Singh's Glamour",
        category: 'Salon & Appointment Booking',
        benefit: 'Online booking portal with service selection, preferred artist scheduling, and automated client notifications.',
        tech: 'Booking Portal · Service Catalog · Appointment Management · Customer Alerts',
        stat1Label: 'Online Calendar',
        stat1Val: '24/7 Booking',
        stat2Label: 'Notifications',
        stat2Val: 'Automated SMS',
        stat3Label: 'Project Status',
        stat3Val: 'Delivered & Live',
      },
    },
    workflow: {
      eyebrow: '03 / DEVELOPMENT PROCESS',
      title: 'How We Plan, Build & Launch',
      tagline: 'A structured, transparent development approach centered around your business requirements.',
      s1Title: '01 — Understand & Plan',
      s1Desc: 'We understand your business, audience, and goals. Define website structure, functionality, user journey, and technical approach.',
      s2Title: '02 — Design & Prototype',
      s2Desc: 'Translate requirements into a clear, responsive user experience designed intentionally for desktop and mobile.',
      s3Title: '03 — Develop & Integrate',
      s3Desc: 'Build the approved website or system using modern technologies, secure authentication, and robust backend integrations.',
      s4Title: '04 — Test, Launch & Support',
      s4Desc: 'Test functionality, responsiveness, performance, and security before launch, followed by reliable ongoing maintenance.',
    },
    quote: {
      eyebrow: '04 / ESTIMATOR',
      title: 'Interactive Project Quote Configurator',
      tagline: 'Select the exact modules and services you need. Get a transparent, itemized estimate with 50/50 milestone payment terms.',
      step1: 'Step 1: Choose Website Scale',
      step2: 'Step 2: Number of Pages',
      step3: 'Step 3: Commercial Cloud Server',
      step4: 'Step 4: Custom Domain Registration',
      step5: 'Step 5: Interactive Modules & Features',
      step6: 'Step 6: AI Automation Copilot',
      step7: 'Step 7: Search Engine Setup',
      summaryTitle: 'Project Scope & Estimated Cost',
      totalPrice: 'Total Project Estimate',
      advancePayment: '50% Milestone Advance (Sprint Start)',
      completionPayment: '50% Balance on Live Approval',
      bookSprint: '🚀 Start Your Project with 50/50 Milestone Model',
    },
    about: {
      eyebrow: '05 / ABOUT FIXKAR',
      title: 'Technology Built Around Real Business Needs',
      tagline: 'Fixkar Web Development builds modern websites and custom web solutions for businesses that need more than just a basic online presence.',
      headline: 'Professional development + modern technology + reliable support.',
      story: 'From professional business websites to admin dashboards, client portals, and custom management systems, each project begins with understanding what the business actually needs. The focus is simple: clear user experiences, reliable development, thoughtful security, and solutions that can continue growing with your business.',
      zeroBloatTitle: 'BUILT AROUND REQUIREMENTS',
      zeroBloatDesc: 'Planned around your business instead of forcing generic website templates.',
      directAccessTitle: 'CLEAN & MAINTAINABLE',
      directAccessDesc: 'Structured with long-term maintenance and future expansion in mind.',
      trackRecordEyebrow: 'OUR WORK',
      trackRecordTitle: 'Proven Web Systems in Active Use',
      trackRecordTagline: 'We build and launch live platforms that support real business operations.',
      calcQuoteBtn: 'Calculate Project Quote →',
    },
    contact: {
      eyebrow: 'PROJECT ENQUIRY',
      title: 'Have a Project in Mind?',
      tagline: 'Tell us what you are planning. We will understand your requirements and help determine the right approach for your website or web application.',
      formTitle: 'Start Your Project Enquiry',
      formSub: 'We review your requirements and respond within 2 to 4 business hours.',
      nameLabel: 'YOUR NAME *',
      namePlaceholder: 'e.g. Rahul Sharma',
      contactLabel: 'PHONE / WHATSAPP OR EMAIL *',
      contactPlaceholder: '+91 98765 43210 or name@business.com',
      businessLabel: 'BUSINESS NAME / IDEA',
      businessPlaceholder: 'e.g. Apex Institute / S Caterers',
      projectTypeLabel: 'SERVICE REQUIRED',
      messageLabel: 'PROJECT REQUIREMENTS',
      messagePlaceholder: 'Tell us about your website, portal, dashboard, or business requirements...',
      sendBtn: 'Start Your Project →',
      thankYouTitle: 'Thank You for Reaching Out!',
      thankYouDesc: 'Your enquiry has been received. Our team will review your requirements and contact you shortly via WhatsApp or Email.',
      sendAnotherBtn: 'Send Another Enquiry',
      directWaysTitle: 'Direct Communication Channels',
      whatsappLabel: 'WhatsApp Project Desk',
      whatsappSub: 'Quick discussion regarding requirements',
      emailLabel: 'Official Project Email',
      emailSub: 'Detailed project specifications & RFPs',
      hoursLabel: 'Working Hours',
      hoursSub: 'Monday – Saturday: 9:30 AM – 8:30 PM IST',
      guaranteeTitle: 'Direct Developer Collaboration',
      guaranteeDesc: 'You collaborate directly with technical developers who understand your project requirements.',
    },
    footer: {
      tagline: 'Professional web development, custom web applications, and managed digital solutions.',
      servicesTitle: 'SERVICES',
      companyTitle: 'COMPANY',
      directDevTitle: 'DIRECT INQUIRIES',
      copyright: '© 2026 Fixkar Web Development. All rights reserved.',
      ownershipNotice: '100% Source Code & Asset Ownership Transferred to Client upon completion.',
    },
  },
  hi: {
    nav: {
      brandTag: 'वेब डेवलपमेंट',
      home: 'होम',
      services: 'सेवाएं',
      work: 'हमारे प्रोजेक्ट्स',
      howItWorks: 'प्रक्रिया',
      about: 'हमारे बारे में',
      contact: 'संपर्क करें',
      getQuote: 'कीमत जानें',
    },
    hero: {
      tag: 'फ़िक्सकार / वेब डेवलपमेंट एवं डिजिटल सॉल्यूशंस',
      headlinePre: 'वेबसाइट्स और वेब सिस्टम्स',
      headlineAccent: 'जो आपके बिजनेस के अनुकूल हों।',
      description:
        'प्रोफेशनल बिजनेस वेबसाइट्स से लेकर कस्टम पोर्टल्स, डैशबोर्ड्स और वेब एप्लिकेशन्स तक—फ़िक्सकार आपके बिजनेस की वास्तविक आवश्यकताओं के अनुसार सुरक्षित और आधुनिक डिजिटल सॉल्यूशंस तैयार करता है।',
      ctaPrimary: 'प्रोजेक्ट शुरू करें →',
      ctaAI: 'फ़िक्सकार AI से बात करें 🤖',
      ctaSecondary: 'हमारे प्रोजेक्ट्स देखें',
      metricUptime: 'बिजनेस फोकस्ड',
      metricUptimeLabel: 'आवश्यकताओं के अनुसार निर्माण (नो जेनेरिक टेम्पलेट्स)',
      metricSpeed: 'पूर्ण स्वामित्व',
      metricSpeedLabel: '100% कोड और एसेट ओनरशिप',
      metricDelivery: 'सीधा संपर्क',
      metricDeliveryLabel: 'सीनियर डेवलपर से सीधा सहयोग',
    },
    trust: {
      label: 'असली बिजनेस के लिए तैयार किए गए लाइव प्रोडक्शन सिस्टम्स',
      sub: 'भारतीय व्यवसायों के संचालन को गति देने वाले लाइव वेब सिस्टम्स',
    },
    homeFacts: {
      eyebrow: 'फ़िक्सकार क्यों चुनें',
      title: 'बिजनेस की वास्तविक जरूरतों के लिए तैयार तकनीक',
      tagline: 'प्रत्येक प्रोजेक्ट की शुरुआत आपके काम करने के तरीके को समझकर होती है, न कि किसी रेडीमेड टेम्पलेट को थोपकर।',
      c1Badge: 'साफ एवं टिकाऊ कोड',
      c1Title: 'आधुनिक डेवलपमेंट',
      c1Desc: 'आधुनिक वेब तकनीकों के साथ तैयार साफ और मेंटेन करने योग्य सॉल्यूशंस जो भविष्य में आसानी से बढ़ सकें।',
      c2Badge: 'बिजनेस फोकस्ड',
      c2Title: 'आपके वर्कफ्लो के अनुसार',
      c2Desc: 'एडमिन डैशबोर्ड से लेकर स्टूडेंट पोर्टल तक, हर फीचर इस तरह डिजाइन किया जाता है जैसे आपका बिजनेस चलता है।',
      c3Badge: 'सुरक्षा एवं निरंतर सपोर्ट',
      c3Title: 'सुरक्षा और तकनीकी सहायता',
      c3Desc: 'ऑथेंटिकेशन, डेटा एक्सेस और संवेदनशील फीचर्स को सुरक्षा मानकों के साथ विकसित किया जाता है, निरंतर सपोर्ट के साथ।',
      ctaTag: 'क्या आपका कोई प्रोजेक्ट है?',
      ctaTitle: 'आइए आपके बिजनेस के लिए सही वेब सॉल्यूशन तैयार करें।',
      ctaDesc: 'हमारे लाइव प्रोजेक्ट्स देखें या अपनी आवश्यकताओं पर चर्चा करें।',
      ctaQuoteBtn: 'प्रोजेक्ट कोटेशन जानें →',
      ctaWorkBtn: 'हमारे प्रोजेक्ट्स देखें',
    },
    services: {
      eyebrow: '01 / हमारी सेवाएं',
      title: 'वेब डेवलपमेंट एवं डिजिटल सॉल्यूशंस',
      tagline: 'प्रोफेशनल वेबसाइट्स, कस्टम एप्लिकेशन्स और मैनेज्ड टेक्निकल सर्विसेज जो आपके बिजनेस लक्ष्यों को पूरा करें।',
      s1: {
        num: '01',
        title: 'वेबसाइट डेवलपमेंट',
        desc: 'आपके ब्रांड, दर्शकों और लक्ष्यों के अनुकूल तैयार प्रोफेशनल वेबसाइट्स—कंपनी वेबसाइट्स और पोर्टफोलियो से लेकर एजुकेशन व सर्विस प्लेटफॉर्म्स तक।',
        tech: ['बिजनेस वेबसाइट्स', 'इंस्टीट्यूट पोर्टल्स', 'रिस्पॉन्सिव डिजाइन', 'SEO रेडी', 'फास्ट लोड'],
      },
      s2: {
        num: '02',
        title: 'कस्टम वेब एप्लिकेशन्स',
        desc: 'कस्टम पोर्टल्स, डैशबोर्ड्स, मैनेजमेंट सिस्टम्स और वेब टूल्स जो आपके वर्कफ्लो और दैनिक संचालन के अनुसार तैयार किए जाते हैं।',
        tech: ['एडमिन डैशबोर्ड्स', 'क्लाइंट पोर्टल्स', 'ऑथेंटिकेशन', 'रोल मैनेजमेंट', 'क्लाउड डेटाबेस'],
      },
      s3: {
        num: '03',
        title: 'ई-कॉमर्स डेवलपमेंट',
        desc: 'प्रोडक्ट मैनेजमेंट, ऑर्डर्स, कस्टमर एक्सपीरियंस, पेमेंट्स और एडमिन कंट्रोल्स के साथ आधुनिक ऑनलाइन स्टोर्स।',
        tech: ['प्रोडक्ट कैटलॉग', 'ऑर्डर मैनेजमेंट', 'UPI व कार्ड पेमेंट्स', 'कस्टमर अकाउंट्स'],
      },
      s4: {
        num: '04',
        title: 'मेंटेनेंस एवं मैनेज्ड सर्विसेज',
        desc: 'वेबसाइट मेंटेनेंस, होस्टिंग मैनेजमेंट, बैकअप्स, सिक्योरिटी सपोर्ट और OTP/मोबाइल वेरिफिकेशन जैसी तकनीकी सेवाएं।',
        tech: ['वेबसाइट मेंटेनेंस', 'होस्टिंग मैनेजमेंट', 'बैकअप्स व सुरक्षा', 'OTP वेरिफिकेशन'],
      },
    },
    work: {
      eyebrow: '02 / हमारे प्रोजेक्ट्स',
      title: 'असली बिजनेस के लिए तैयार किए गए लाइव प्रोजेक्ट्स',
      tagline: 'हॉस्पिटैलिटी, इलेक्ट्रॉनिक्स और सर्विस बुकिंग के लिए तैयार किए गए हमारे लाइव प्लेटफॉर्म्स देखें।',
      scaterers: {
        title: 'एस कैटरर्स एंड इवेंट्स',
        category: 'हॉस्पिटैलिटी एवं इवेंट मैनेजमेंट',
        benefit: 'इंटरैक्टिव मेन्यू प्लानिंग, प्रति-प्लेट कीमत अनुमान और सीधे व्हाट्सएप इन्क्वायरी के साथ कस्टम कैटरिंग प्लेटफॉर्म।',
        tech: 'वेबसाइट · इंटरैक्टिव मेन्यू एस्टीमेटर · लीड डिस्पैच · मोबाइल रिस्पॉन्सिव',
        stat1Label: 'मेन्यू एस्टीमेटर',
        stat1Val: 'इंटरैक्टिव फ्लो',
        stat2Label: 'लीड डिस्पैच',
        stat2Val: 'सीधा व्हाट्सएप',
        stat3Label: 'प्रोजेक्ट स्टेटस',
        stat3Val: 'लाइव व एक्टिव',
      },
      ecofone: {
        title: 'इकोफोन (Ecofone)',
        category: 'ई-कॉमर्स एवं डिवाइस मूल्यांकन',
        benefit: 'स्मार्टफोन ट्रेड-इन प्लेटफॉर्म जहां 3 आसान स्टेप्स में डिवाइस का सटीक मूल्यांकन और पेमेंट गेटवे इंटीग्रेशन मिलता है।',
        tech: 'ई-कॉमर्स · मूल्यांकन इंजन · एडमिन डैशबोर्ड · UPI पेमेंट्स',
        stat1Label: 'डिवाइस मूल्यांकन',
        stat1Val: '3-स्टेप फ्लो',
        stat2Label: 'पेमेंट गेटवे',
        stat2Val: 'रेज़रपे UPI',
        stat3Label: 'प्रोजेक्ट स्टेटस',
        stat3Val: 'लाइव व एक्टिव',
      },
      singhs: {
        title: "सिंह्स ग्लैमर (Singh's Glamour)",
        category: 'सैलून एवं अपॉइंटमेंट बुकिंग',
        benefit: 'सर्विस चयन, पसंदीदा आर्टिस्ट शेड्यूलिंग और ऑटोमैटिक क्लाइंट नोटिफिकेशन्स के साथ ऑनलाइन बुकिंग पोर्टल।',
        tech: 'बुकिंग पोर्टल · सर्विस कैटलॉग · अपॉइंटमेंट मैनेजमेंट · कस्टमर अलर्ट्स',
        stat1Label: 'ऑनलाइन कैलेंडर',
        stat1Val: '24/7 बुकिंग',
        stat2Label: 'नोटिफिकेशन्स',
        stat2Val: 'ऑटोमैटिक SMS',
        stat3Label: 'प्रोजेक्ट स्टेटस',
        stat3Val: 'लाइव व एक्टिव',
      },
    },
    workflow: {
      eyebrow: '03 / डेवलपमेंट प्रक्रिया',
      title: 'हम कैसे प्लान, निर्माण और लॉन्च करते हैं',
      tagline: 'आपकी व्यावसायिक आवश्यकताओं पर केंद्रित एक संरचित और पारदर्शी विकास प्रक्रिया।',
      s1Title: '01 — समझना एवं प्लानिंग',
      s1Desc: 'हम आपके व्यवसाय, दर्शकों और लक्ष्यों को समझते हैं। वेबसाइट संरचना, कार्यक्षमता और तकनीकी दृष्टिकोण तय करते हैं।',
      s2Title: '02 — डिजाइन एवं प्रोटोटाइप',
      s2Desc: 'आवश्यकताओं को डेस्कटॉप और मोबाइल के लिए एक स्पष्ट और रिस्पॉन्सिव यूजर एक्सपीरियंस में बदलते हैं।',
      s3Title: '03 — डेवलपमेंट एवं इंटीग्रेशन',
      s3Desc: 'आधुनिक तकनीकों, सुरक्षित ऑथेंटिकेशन और मजबूत बैकएंड इंटीग्रेशन के साथ सिस्टम का निर्माण करते हैं।',
      s4Title: '04 — टेस्टिंग, लॉन्च एवं सपोर्ट',
      s4Desc: 'लॉन्च से पहले कार्यप्रणाली, गति और सुरक्षा की पूरी जांच, जिसके बाद निरंतर तकनीकी सपोर्ट उपलब्ध रहता है।',
    },
    quote: {
      eyebrow: '04 / एस्टीमेटर',
      title: 'इंटरैक्टिव प्रोजेक्ट कोटेशन कॉन्फिगरेटर',
      tagline: 'जरूरी मॉड्यूल्स और सेवाएं चुनें और 50/50 माइलस्टोन पेमेंट के साथ पारदर्शी अनुमान प्राप्त करें।',
      step1: 'स्टेप 1: वेबसाइट का प्रकार चुनें',
      step2: 'स्टेप 2: पेजों की संख्या',
      step3: 'स्टेप 3: कमर्शियल क्लाउड सर्वर',
      step4: 'स्टेप 4: कस्टम डोमेन रजिस्ट्रेशन',
      step5: 'स्टेप 5: जरूरी फीचर्स व मॉड्यूल्स',
      step6: 'स्टेप 6: एआई ऑटोमेशन कोपायलट',
      step7: 'स्टेप 7: सर्च इंजन सेटअप',
      summaryTitle: 'प्रोजेक्ट स्कोप व अनुमानित बजट',
      totalPrice: 'कुल अनुमानित लागत',
      advancePayment: '50% माइलस्टोन एडवांस (शुरुआत पर)',
      completionPayment: '50% बैलेंस (अप्रूवल व लाइव होने पर)',
      bookSprint: '🚀 50/50 मॉडल के साथ प्रोजेक्ट शुरू करें',
    },
    about: {
      eyebrow: '05 / फ़िक्सकार के बारे में',
      title: 'बिजनेस की वास्तविक जरूरतों के लिए तैयार तकनीक',
      tagline: 'फ़िक्सकार वेब डेवलपमेंट उन व्यवसायों के लिए आधुनिक वेबसाइट्स और कस्टम सॉल्यूशंस बनाता है जिन्हें सिर्फ एक बेसिक पेज से ज्यादा की जरूरत है।',
      headline: 'प्रोफेशनल डेवलपमेंट + आधुनिक तकनीक + विश्वसनीय सपोर्ट।',
      story: 'प्रोफेशनल बिजनेस वेबसाइट्स से लेकर एडमिन डैशबोर्ड्स, क्लाइंट पोर्टल्स और कस्टम मैनेजमेंट सिस्टम्स तक—प्रत्येक प्रोजेक्ट यह समझकर शुरू होता है कि व्यवसाय को वास्तव में क्या चाहिए। हमारा फोकस स्पष्ट यूजर एक्सपीरियंस, मजबूत डेवलपमेंट और सुरक्षा पर है।',
      zeroBloatTitle: 'आवश्यकताओं के अनुसार निर्माण',
      zeroBloatDesc: 'जेनेरिक वेबसाइट टेम्पलेट्स थोपने के बजाय आपके व्यवसाय के अनुसार योजना।',
      directAccessTitle: 'साफ एवं टिकाऊ कोड',
      directAccessDesc: 'भविष्य के विस्तार और आसान मेंटेनेंस को ध्यान में रखकर तैयार।',
      trackRecordEyebrow: 'हमारा काम',
      trackRecordTitle: 'सक्रिय उपयोग में लाइव वेब सिस्टम्स',
      trackRecordTagline: 'हम ऐसे लाइव प्लेटफॉर्म्स बनाते हैं जो वास्तविक व्यावसायिक संचालन का समर्थन करते हैं।',
      calcQuoteBtn: 'प्रोजेक्ट कोटेशन जानें →',
    },
    contact: {
      eyebrow: 'प्रोजेक्ट इन्क्वायरी',
      title: 'क्या आपका कोई प्रोजेक्ट है?',
      tagline: 'बताएं आप क्या प्लान कर रहे हैं। हम आपकी आवश्यकताओं को समझेंगे और आपकी वेबसाइट या वेब एप्लिकेशन के लिए सही दृष्टिकोण तय करने में मदद करेंगे।',
      formTitle: 'प्रोजेक्ट इन्क्वायरी शुरू करें',
      formSub: 'हम आपकी आवश्यकताओं की समीक्षा करते हैं और 2 से 4 व्यावसायिक घंटों में जवाब देते हैं।',
      nameLabel: 'आपका नाम *',
      namePlaceholder: 'उदा. राहुल शर्मा',
      contactLabel: 'फोन / व्हाट्सएप या ईमेल *',
      contactPlaceholder: '+91 98765 43210 या name@business.com',
      businessLabel: 'बिजनेस का नाम / आइडिया',
      businessPlaceholder: 'उदा. अपेक्स इंस्टीट्यूट / एस कैटरर्स',
      projectTypeLabel: 'आवश्यक सेवा',
      messageLabel: 'प्रोजेक्ट आवश्यकताएं',
      messagePlaceholder: 'अपनी वेबसाइट, पोर्टल, डैशबोर्ड या बिजनेस आवश्यकताओं के बारे में बताएं...',
      sendBtn: 'प्रोजेक्ट शुरू करें →',
      thankYouTitle: 'संपर्क करने के लिए धन्यवाद!',
      thankYouDesc: 'आपकी इन्क्वायरी प्राप्त हो गई है। हमारी टीम जल्द ही व्हाट्सएप या ईमेल द्वारा आपसे संपर्क करेगी।',
      sendAnotherBtn: 'दूसरी इन्क्वायरी भेजें',
      directWaysTitle: 'सीधे संपर्क सूत्र',
      whatsappLabel: 'व्हाट्सएप प्रोजेक्ट डेस्क',
      whatsappSub: 'आवश्यकताओं पर त्वरित चर्चा',
      emailLabel: 'आधिकारिक प्रोजेक्ट ईमेल',
      emailSub: 'विस्तृत प्रोजेक्ट विवरण एवं प्रस्ताव',
      hoursLabel: 'कार्य समय',
      hoursSub: 'सोमवार – शनिवार: सुबह 9:30 से रात 8:30 IST',
      guaranteeTitle: 'सीधा डेवलपर सहयोग',
      guaranteeDesc: 'आप सीधे उन डेवलपर्स के साथ काम करते हैं जो आपके प्रोजेक्ट की तकनीकी आवश्यकताओं को समझते हैं।',
    },
    footer: {
      tagline: 'प्रोफेशनल वेब डेवलपमेंट, कस्टम वेब एप्लिकेशन्स और मैनेज्ड डिजिटल सॉल्यूशंस।',
      servicesTitle: 'सेवाएं',
      companyTitle: 'कंपनी',
      directDevTitle: 'सीधी इन्क्वायरी',
      copyright: '© 2026 फ़िक्सकार वेब डेवलपमेंट। सर्वाधिकार सुरक्षित।',
      ownershipNotice: '100% सोर्स कोड और एसेट ओनरशिप प्रोजेक्ट पूरा होने पर क्लाइंट को हस्तांतरित की जाती है।',
    },
  },
};

const LanguageContext = createContext();

function normalizeLang(code) {
  if (!code) return 'en';
  const lower = String(code).toLowerCase().trim();
  if (lower === 'hi' || lower === 'hindi' || lower.includes('hind')) return 'hi';
  return 'en';
}

export function LanguageProvider({ children }) {
  const [lang, setRawLang] = useState('en');

  const setLang = (newLang) => {
    setRawLang(normalizeLang(newLang));
  };

  const toggleLanguage = () => {
    setRawLang((prev) => (prev === 'en' ? 'hi' : 'en'));
  };

  const safeLang = normalizeLang(lang);
  const activeTranslations = translations[safeLang] || translations.en;

  return (
    <LanguageContext.Provider value={{ lang: safeLang, setLang, toggleLanguage, t: activeTranslations }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
